name: bubble_pop
description: "Bubble Pop neon ocean game."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  uuid: ^4.6.0
  dio: ^5.11.0
  pretty_dio_logger: ^1.4.0
  package_info_plus: ^10.2.1
  device_info_plus: ^13.2.0
  android_id: ^0.5.2+1
  play_install_referrer: ^0.5.0
  flutter_timezone: ^5.1.0
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
  advertising_id: ^2.7.1
  adjust_sdk: ^5.7.1
  appsflyer_sdk: ^6.18.1
  onesignal_flutter: ^5.6.7
  wakelock_plus: ^1.7.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
